name: Deploy to Vercel

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#   AWS_S3_BUCKET_STATIC: 'ftr-upload-widget-web-static'
#   AWS_S3_BUCKET_CDN: 'shandryll-upload-widget-web-cdn'
#   SOURCE_DIST: './dist'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install vercel
        id: install-vercel
        run: |
          npm install --global vercel@latest

      - name: Pull vercel config
        id: pull-vercel-config
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Vercel build app
        id: vercel-build-app
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy vercel app
        id: deploy-vercel-app
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Install dependencies
      #   id: install-dependencies
      #   run: |
      #     pnpm install

      # - name: Build app
      #   id: build-app
      #   run: |
      #     pnpm run build

      # - name: Configure AWS credentials
      #   id: configure-aws-credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ vars.AWS_REGION }}

      # - name: Sync files to S3
      #   id: sync-files-to-s3
      #   run: |
      #     aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_STATIC }}/ --delete --exclude '.*git*'

      # - name: Sync files to S3 CDN
      #   id: sync-files-to-s3-cdn
      #   run: |
      #     aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_CDN }}/ --delete --exclude '.*git*'

      # - name: Invalidate CDN cache
      #   id: invalidate-cdn-cache
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
